## **Imports**

In [1]:
## Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
## Importing the OS and JSON Modules
import os,json

In [3]:
df = pd.read_csv('superhero_info - superhero_info.csv')
df.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [21]:
df['Measurements'].str.split(' ',expand=True)

              0       1     2          3       4     5
0    {'Height':  '203.0  cm',  'Weight':  '441.0  kg'}
1    {'Height':  '191.0  cm',  'Weight':   '65.0  kg'}
2    {'Height':  '185.0  cm',  'Weight':   '90.0  kg'}
3    {'Height':  '203.0  cm',  'Weight':  '441.0  kg'}
4    {'Height':  '193.0  cm',  'Weight':  '122.0  kg'}
..          ...     ...   ...        ...     ...   ...
458  {'Height':  '183.0  cm',  'Weight':   '83.0  kg'}
459  {'Height':  '165.0  cm',  'Weight':   '52.0  kg'}
460  {'Height':   '66.0  cm',  'Weight':   '17.0  kg'}
461  {'Height':  '170.0  cm',  'Weight':   '57.0  kg'}
462  {'Height':  '185.0  cm',  'Weight':   '81.0  kg'}

[463 rows x 6 columns]

In [22]:
df[['h','Height_cm','cm', 'w','weight_kg', 'kg']] = df['Measurements'].str.split(' ',expand=True)
df.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Height_cm,weight_kg,h,cm,w,kg
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",'203.0,'441.0,{'Height':,"cm',",'Weight':,kg'}
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",'191.0,'65.0,{'Height':,"cm',",'Weight':,kg'}

In [23]:
df = df.drop('Measurements', axis=1)
df = df.drop('h', axis=1)
df = df.drop('w', axis=1)
df = df.drop('cm', axis=1)
df = df.drop('kg', axis=1)

In [24]:
df.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Height_cm,weight_kg
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,'203.0,'441.0
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,'191.0,'65.0

In [30]:
df['Height_cm'] = df.Height_cm.str.extract(r'(\d+)', expand=True).astype(int)

AttributeError: Can only use .str accessor with string values!

In [27]:
df.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Height_cm,weight_kg
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,203,'441.0
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,191,'65.0

In [31]:
df['weight_kg'] = df.weight_kg.str.extract(r'(\d+)', expand=True).astype(int)

In [32]:
df.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Height_cm,weight_kg
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,203,441
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,191,65

In [33]:
df[['Hero','Publisher']] = df['Hero|Publisher'].str.split('|',expand=True)
df.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Height_cm,weight_kg,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,203,441,A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,191,65,Abe Sapien,Dark Horse Comics

In [34]:
df = df.drop('Hero|Publisher', axis=1)
df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Height_cm,weight_kg,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,203,441,A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,191,65,Abe Sapien,Dark Horse Comics

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Height_cm   463 non-null    int32
 7   weight_kg   463 non-null    int32
 8   Hero        463 non-null    object
 9   Publisher   463 non-null    object
dtypes: int32(2), object(8)
memory usage: 32.7+ KB

In [114]:
df_powers = pd.read_csv('superhero_powers - superhero_powers.csv')
df_powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [115]:
df_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [116]:
df_powers.loc[2,'Powers']

'Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,Telepathy,Stamina,Immortality,Reflexes,Enhanced Sight,Sub-Mariner'

In [117]:
df_powers.head(2)

  hero_names                                             Powers
0    3-D Man         Agility,Super Strength,Stamina,Super Speed
1     A-Bomb  Accelerated Healing,Durability,Longevity,Super...

In [118]:
df_powers['Power_split'] = df_powers.Powers.str.split(',')

In [119]:

df_powers.head(2)

,hero_names,Powers,Power_split
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","[Agility, Super Strength, Stamina, Super Speed]"
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S..."

In [120]:
df_powers['Power_split'].value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[Intelligence]                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
[Durability, Super Strength]                                                                                                                                                                                                                                                                                                                                                                                                                                     5
[Teleportation]                                                                                                                                                                                                                                                                                                                                                                                                                                                  4
[Marksmanship]                                                                                                                                                                                                                                                                                                                                                                                                                                                   4
[Electrokinesis]                                                                                                                                                                                                                                                                                                                                                                                                                                                 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
[Agility, Accelerated Healing, Energy Absorption, Flight, Weapons Master, Super Strength, Energy Blasts, Super Speed, Enhanced Senses, Immortality, Phasing, Invulnerability, Force Fields, Self-Sustenance, Radiation Control, Technopath/Cyberpath, Natural Armor, Enhanced Sight, Molecular Manipulation, Heat Generation, Energy Manipulation, Time Travel, Radiation Immunity, Energy Resistance, Time Manipulation, Invisibility, Radiation Absorption]    1
[Cold Resistance, Flight, Intelligence, Enhanced Senses, Empathy, Heat Resistance, Telepathy Resistance, Weather Control]                                                                                                                                                                                                                                                                                                                                        1
[Weapons Master, Intelligence, Cryokinesis, Energy Blasts, Weapon-based Powers, Electrokinesis, Energy Beams, Self-Sustenance, Mind Control, Molecular Manipulation, Levitation]                                                                                                                                                                                                                                                                                 1
[Durability, Super Strength, Stamina, Telekinesis, Invulnerability, Regeneration, Magnetism]                                                                                                                                                                                                                                                                                                                                                                     1
[Agility, Accelerated Healing, Durability, Energy Absorption, Flight, Intelligence, Super Strength, Stamina, Super Speed, Enhanced Senses, Jump, Enhanced Memory, Reflexes, Invulnerability, Enhanced Hearing, Vision - Telescopic, Toxin and Disease Resistance, Vision - Microscopic, Super Breath, Vision - Night, Vision - Infrared, Vision - Heat, Vision - X-Ray, Vision - Thermal]                                                                        1
Name: Power_split, Length: 608, dtype: int64

In [122]:
exploded = df_powers.explode('Power_split')
exploded[['hero_names','Powers','Power_split']].head(5)

,hero_names,Powers,Power_split
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Agility
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Super Strength
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Stamina
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Super Speed
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Accelerated Healing

In [123]:
## saving the unique values from the exploded column
cols_to_make = exploded['Power_split'].dropna().unique()
cols_to_make

array(['Agility', 'Super Strength', 'Stamina', 'Super Speed',
       'Accelerated Healing', 'Durability', 'Longevity', 'Camouflage',
       'Self-Sustenance', 'Cold Resistance', 'Underwater breathing',
       'Marksmanship', 'Weapons Master', 'Intelligence', 'Telepathy',
       'Immortality', 'Reflexes', 'Enhanced Sight', 'Sub-Mariner',
       'Lantern Power Ring', 'Invulnerability', 'Animation',
       'Super Breath', 'Dimensional Awareness', 'Flight', 'Size Changing',
       'Teleportation', 'Magic', 'Dimensional Travel',
       'Molecular Manipulation', 'Energy Manipulation', 'Power Cosmic',
       'Energy Absorption', 'Elemental Transmogrification',
       'Fire Resistance', 'Natural Armor', 'Heat Resistance',
       'Matter Absorption', 'Regeneration', 'Stealth', 'Power Suit',
       'Energy Blasts', 'Energy Beams', 'Heat Generation', 'Danger Sense',
       'Phasing', 'Force Fields', 'Hypnokinesis', 'Invisibility',
       'Enhanced Senses', 'Jump', 'Shapeshifting', 'Elasticity',
       'Substance Secretion', 'Enhanced Hearing', 'Adaptation', 'Gliding',
       'Natural Weapons', 'Wallcrawling', 'Vision - Thermal',
       'Power Augmentation', 'Cryokinesis', 'Duplication',
       'Weapon-based Powers', 'Fire Control', 'Enhanced Memory',
       'Energy Constructs', 'Power Absorption', 'Time Travel',
       'Enhanced Smell', 'Water Control', 'Vision - Telescopic',
       'Magnetism', 'Vision - Microscopic', 'Vision - Night',
       'Vision - Heat', 'Vision - X-Ray', 'Psionic Powers',
       'Toxin and Disease Resistance', 'Animal Attributes',
       'Animal Oriented Powers', 'Toxin and Disease Control', 'Empathy',
       'Animal Control', 'Darkforce Manipulation', 'Time Manipulation',
       'Reality Warping', 'Web Creation', 'Symbiote Costume',
       'Telekinesis', 'Levitation', 'Biokinesis', 'Sonar',
       'Enhanced Touch', 'Seismic Power', 'Energy Armor',
       'Omnilingualism', 'Radiation Immunity', 'Density Control',
       'Light Control', 'Illumination', 'Molecular Combustion',
       'Astral Travel', 'Precognition', 'Intangibility', 'Illusions',
       'Audio Control', 'Sonic Scream', 'Peak Human Condition',
       'Vision - Infrared', 'Dexterity', 'Omnitrix', 'Omnipotent',
       'Possession', 'Energy Resistance', 'Vision - Cryo', 'Mind Control',
       'Mind Blast', 'Clairvoyance', 'Probability Manipulation',
       'Death Touch', 'Electrokinesis', 'Gravity Control',
       'Technopath/Cyberpath', 'Radar Sense', 'Astral Projection',
       'Cloaking', 'Telepathy Resistance', 'Mind Control Resistance',
       'Hyperkinesis', 'Spatial Awareness', 'Radiation Control',
       'Radiation Absorption', 'Magic Resistance', 'Element Control',
       'Plant Control', 'Terrakinesis', 'Power Sense', 'Wind Control',
       'Qwardian Power Ring', 'Echolocation', 'Resurrection', 'The Force',
       'Summoning', 'Banish', 'Molecular Dissipation',
       'Electrical Transport', 'Speed Force', 'Grim Reaping',
       'Portal Creation', 'Vitakinesis', 'Projection', 'Insanity',
       'Photographic Reflexes', 'Anti-Gravity', 'Thirstokinesis',
       'Power Nullifier', 'Weather Control', 'Omnipresent', 'Omniscient',
       'Hair Manipulation', 'Nova Force', 'Odin Force', 'Phoenix Force',
       'Intuitive aptitude', 'Melting', 'Changing Armor'], dtype=object)

In [124]:
for col in cols_to_make:
    df_powers[col] = df_powers['Powers'].str.contains(col)
df_powers.head()

,hero_names,Powers,Power_split,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","[Agility, Super Strength, Stamina, Super Speed]",True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S...",False,True,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...","[Agility, Accelerated Healing, Cold Resistance...",True,True,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,Lantern Power Ring,[Lantern Power Ring],False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...","[Accelerated Healing, Intelligence, Super Stre...",False,True,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [125]:
df_powers = df_powers.drop(columns=['Powers','Power_split'])

In [126]:
df_powers.head(2)

,hero_names,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,Camouflage,Self-Sustenance,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,True,True,True,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,True,False,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False

In [127]:
df_powers.rename(columns = {'hero_names':'Hero'}, inplace = True)

In [128]:
new_df= pd.merge(df,df_powers, on='Hero')

In [129]:
new_df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Height_cm,weight_kg,Hero,Publisher,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,Male,Human,good,No Hair,yellow,Unknown,203,441,A-Bomb,Marvel Comics,...,False,False,False,False,False,False,False,False,False,False
1,Male,Icthyo Sapien,good,No Hair,blue,blue,191,65,Abe Sapien,Dark Horse Comics,...,False,False,False,False,False,False,False,False,False,False